#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data

# Use awk to extract the visitor IP and HTTP status code from the Apache log file
# Then use sort and uniq to count the occurrences of each combination of IP and HTTP status code
# Finally, use awk to format the output
awk '{print $1, $9}' apache-access.log | sort | uniq -c | awk '{print $1, $2, $3}' | sort -rn
