#!/usr/bin/env bash

# Check if the key pair already exists
if [ -f ~/.ssh/school ]; then
    echo "Key pair already exists."
    exit 1
fi

# Generate the RSA key pair
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty"

echo "Key pair created successfully."
